# Generated by Django 4.1.7 on 2023-03-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя актера')),
                ('surname', models.CharField(max_length=70, verbose_name='Фамилия актера')),
                ('old', models.IntegerField(blank=True, null=True, verbose_name='Возраст актера')),
                ('history', models.TextField(verbose_name='История актера')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/actors', verbose_name='Фото актера')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='Слаг категории')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(verbose_name='Описание жанра')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя продюсера')),
                ('surname', models.CharField(max_length=70, verbose_name='Фамилия продюсера')),
                ('old', models.IntegerField(blank=True, null=True, verbose_name='Возраст продюсера')),
                ('history', models.TextField(verbose_name='История продюсера')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/producers', verbose_name='Фото продюсера')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/movies', verbose_name='Картинка фильма')),
                ('release_date', models.DateTimeField(verbose_name='Дата выхода фильма')),
                ('country', models.CharField(max_length=70, verbose_name='Страна производитель')),
                ('actors', models.ManyToManyField(to='movies.actor', verbose_name='Актеры фильма')),
                ('genre', models.ManyToManyField(to='movies.genre', verbose_name='Жанр фильма')),
                ('producer', models.ForeignKey(default='Не задано', on_delete=django.db.models.deletion.SET_DEFAULT, to='movies.producer', verbose_name='Продюсер фильма')),
            ],
        ),
    ]
