# Generated by Django 4.1.7 on 2023-03-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors', verbose_name='Фото актера'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies', verbose_name='Картинка фильма'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='producers', verbose_name='Фото продюсера'),
        ),
    ]
